#!"C:\Users\SERIF\Desktop\nese\dyn and soc netw\simulation tool\netsim\crowdenv\Scripts\python.exe"
# EASY-INSTALL-SCRIPT: 'python-louvain==0.16','community'
__requires__ = 'python-louvain==0.16'
__import__('pkg_resources').run_script('python-louvain==0.16', 'community')
